###
POST http://localhost/users
Content-Type: application/json

{
  "id": "e49b2af6-c3d8-48f7-a7e5-f383f93ed901",
  "name": "Andreu2",
  "surname": "Garcia",
  "email": "test2@test.com",
  "password": "hash"
}

###
GET http://localhost/users
Content-Type: application/json

###
GET http://localhost:80/users/e49b2af6-c3d8-48f7-a7e5-f283f93ed900
Content-Type: application/json

###
PUT http://localhost:80/update/1
Content-Type: application/json

{
  "id": "e49b2af6-c3d8-48f7-a7e5-f383f93ed900",
  "name": "updated!",
  "surname": "aaaaaa",
  "email": "bbbbb",
  "password": "<<<<<<<"
}

###
DELETE http://localhost:80/delete/e49b2af6-c3d8-48f7-a7e5-f283f93ed900
Content-Type: application/json

###
DELETE http://localhost:80/deleteUser
Content-Type: application/json

{
  "id": "e49b2af6-c3d8-48f7-a7e5-f383f93ed900",
  "name": "a",
  "surname": "",
  "email": "",
  "password": ""
}

###
GET localhost/users/search?
    order.orderBy=name
    &order.orderType=DESC
    &filters%5B0%5D.field=name
    &filters%5B0%5D.operator=EQUAL
    &filters%5B0%5D.value=Andreu2
    &page=0
    &size=1
