spring:
  mvc:
    problemdetails:
      enabled: true
  application:
    name: User-Crud
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update