spring:

  mvc:
    problemdetails:
      enabled: true
  application:
    name: User-Crud
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/users
    username: user-crud
    password: user-crud
  jpa:
    hibernate:
      ddl-auto: update
